Creation of functions to set intervals after verification
billdenney/pknca pull request #335
Opened 2024-11-07 20:48 UTC by DBartlettHP

Here is the first pass of the creation of functions noted in issue #329 .

If the functions look to do the expected tasks, I will begin on elaborate testing.

2024-11-07 20:50 UTC, DBartlettHP commented
@billdenney Let me know if these functions are too simple or not.

Also, I want to note that I have both functions inside a single script file since they are very related.
Can I also test both of these functions within the same test script?

2024-11-08 03:45 UTC, billdenney commented
> @billdenney Let me know if these functions are too simple or not.
> 
> Also, I want to note that I have both functions inside a single script file since they are very related. Can I also test both of these functions within the same test script?

Yes, multiple related functions should go into the same file.

> Edit: Further on I noticed something within testing.
> 
> * To appropriately test `assert_intervals`, I would need a PKNCAdata object.
> * In order to have a PKNCAdata object, I need to input intervals (in the case that dose is not given)
> 
> These two ideas seem to cause me some confusion. [Is this expected?]

The initial intervals would be a data.frame. They get tested with a PKNCAdata object that may or may not yet have the intervals added. And, the core test is related to the group column names in the PKNCAconc object. Does that make it clearer?

2024-11-10 22:49 UTC, DBartlettHP commented
Understood, here are some further notes:

`set_intervals` will automatically set the intervals, after verification, in the `PKNCAdata` object, and return the `PKNCAdata` object.

`set_intervals` must then be used within the conditional statement `if (missing(intervals))` inside the `PKNCA.default` function. [This caused me to move the class assignment to the front of the function, due to the verifications being used]

These changes have caused 5 tests to fails, which I am looking into:

          "The following columns in 'intervals' are not allowed"  

Where we see some tests using the interval columns:
- impute
- conc_above (i assume time_above also fails)
- aucinf
- foo

2024-11-13 18:21 UTC, billdenney requested changes
Please add a note to the news file, too.

2024-11-13 18:21 UTC, billdenney commented on R/set_and_assert_intervals.R
> +  return(data)
Please use the implicit return code style (remove the `return()` and just use `data`) rather than using `return(data)`.

2024-11-13 18:21 UTC, billdenney commented on R/set_and_assert_intervals.R
> +  return(intervals)
Please use the implicit return code style.

2024-11-13 18:21 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +})
Please also add a test for `set_intervals()`.

2024-11-13 18:27 UTC, billdenney commented
> These changes have caused 5 tests to fail, which I am looking into:
> 
> ```
>       "The following columns in 'intervals' are not allowed"  
> ```
> 
> Where we see some tests using the interval columns:
> 
> * impute
> * conc_above (i assume time_above also fails)
> * aucinf
> * foo

Can you please link to the test file lines that are failing?

For `aucinf`, that is probably an error where something else like aucinf.obs was intended. That test should probably be modified.

conc_above and time_above likely need some way to add them to the intervals list in some way.

impute should be added as a special case like start and end.

foo was likely an intentional test of something else. I would need to see where the error occurs to know what to do.

2024-11-13 19:38 UTC, DBartlettHP commented
Here are the links for the failing tests: 

[IMPUTE](https://github.com/billdenney/pknca/blob/main/tests/testthat/test-impute.R#L231)
[IMPUTE2](https://github.com/billdenney/pknca/blob/main/tests/testthat/test-impute.R#L253-L259)
[PK.CALC.ALL](https://github.com/billdenney/pknca/blob/main/tests/testthat/test-pk.calc.all.R#L462-L468)
[PK.CALC.ALL2](https://github.com/billdenney/pknca/blob/main/tests/testthat/test-pk.calc.all.R#L590-L603)
[PK.CALC.ALL3](https://github.com/billdenney/pknca/blob/main/tests/testthat/test-pk.calc.all.R#L640-L647)

2024-11-13 20:27 UTC, DBartlettHP commented
So far:

- IMPUTE and IMPUTE2: [IDEA] Perhaps it can simply be added into the `allowed_columns`. This seems viable due to the fact that the imputation method is used _**when the colnames of the intervals contains "impute"**_ 

- PK.CALC.ALL: [CORRECTED] `time_above` and `conc_above` have been added to the `allowed_columns`

- PK.CALC.ALL2: [CORRECTED] unexpected columns now throw an error. An error is expected in the test now.

- PK.CALC.ALL3: [IDEA] Perhaps the `keep.interval_cols()` option needs to also do something inside the `allowed_columns` within `assert_intervals`

2024-11-15 21:17 UTC, billdenney commented
> * IMPUTE and IMPUTE2: [IDEA] Perhaps it can simply be added into the `allowed_columns`. This seems viable due to the fact that the imputation method is used _**when the colnames of the intervals contains "impute"**_

Yes, "impute" can be added to the `allowed_columns`

> * PK.CALC.ALL: [CORRECTED] `time_above` and `conc_above` have been added to the `allowed_columns`

Yes, `time_above` and `conc_above` can be added to the `allowed_columns`

> * PK.CALC.ALL2: [CORRECTED] unexpected columns now throw an error. An error is expected in the test now.

That's the right change.

> * PK.CALC.ALL3: [IDEA] Perhaps the `keep.interval_cols()` option needs to also do something inside the `allowed_columns` within `assert_intervals`

`keep_interval_cols` is an important exception. Yes, `keep_interval_cols` should prevent errors in `assert_intervals()`.

2024-12-04 19:53 UTC, DBartlettHP commented
@billdenney 
The latest commit has completed all the suggestions properly, and `devtools::check()` runs through as before.

This should be ready for merging.

2024-12-06 22:04 UTC, billdenney requested changes

2024-12-06 22:04 UTC, billdenney commented on R/001-add.interval.col.R
> +# add.interval.col(
Remove, please

2024-12-06 22:04 UTC, billdenney commented on R/class-PKNCAdata.R
> +  ret <- set_intervals(ret, intervals)
Please give argument names.

2024-12-06 22:04 UTC, billdenney commented on R/set_and_assert_intervals.R
> +  if (class(data)[1] != "PKNCAdata") {
Please change to `!inherits(data, "PKNCAdata")`

2024-12-06 22:04 UTC, billdenney commented on R/set_and_assert_intervals.R
> +  ifelse("keep_interval_cols" %in% names(data$options),
Please replace with:

```
  allowed_columns <-
    c(
      names(getGroups.PKNCAdata(data)),
      names(get.interval.cols()),
      "conc_above",
      "time_above",
      "impute",
      # If not used, data$options$keep_interval_cols will be NULL
      data$options$keep_interval_cols
    )
```

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-pk.calc.all.R
> +test_that("Unexpected interval columns now not cause an error (#238)", {
Add to the NEWS file that this is different now.

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +  result <- assert_intervals(intervals = data.frame(start = 0, end = 1, cmax = TRUE), o_data)
Please use argument names.

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +  result <- assert_intervals(intervals = data.frame(start = 0, end = 1, cmax = TRUE), o_data)
Please use argument names.

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +  expect_error(assert_intervals(non_df_intervals, o_data),
Please use argument names.

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +               "The 'data' argument must be a PKNCAdata object.")
Please name this argument `regex` and add the argument `fixed = TRUE`.

2024-12-06 22:04 UTC, billdenney commented on tests/testthat/test-set_and_assert_intervals.R
> +  expect_error(assert_intervals(invalid_intervals, o_data),
Please name arguments and add the `regex` and `fixed` arguments.

2024-12-07 20:19 UTC, DBartlettHP commented
Suggestions have been made. (This should be ready for merging)

2024-12-07 20:29 UTC, billdenney approved these changes

2024-12-07 20:29 UTC, billdenney commented
Thanks!

2024-12-07 20:29 UTC, merged